### ISSUE TITLE
sbt-build-info-conf introduces build classpath conflicts

### ISSUE THREAD

**Issue by otrebski** [Sensatus/sbt-build-info-conf#4]
`sbt-build-info-conf` requires pretty old `jgit 3.7`. If other plugin is using `https://github.com/sbt/sbt-git`, sbt is using `jgit 4.x` which is not backward compatible with `jgit 3.7`. In result calling `sbt ...` is ends up with `NoSuchMethodError`.

Solution:

Use `sbt-git` instead of direct dependency to jgit. PR is here: https://github.com/timetotrade/sbt-build-info-conf/pull/3

**Comment by psliwa** [comment]
+1

**Comment by DomBlack** [comment]
Merged in #3
